### PR TITLE
Sync up L10N messaging in saved.js with signup.js

### PR DESCRIPTION
**Pull request by gijsk**
Not 100% necessary, but probably saves confusion in the long run if we do reuse these strings. It would be better if there was a shared place for this stuff, but I couldn't find one.

### CODE REVIEW

**Comment by gijsk** [comment]
@mixedpuppy and/or @ideashower , is this sane or am I missing something? (I don't have a local setup to test this with, so I just hope my copy/paste and tweaking was successful...)

**Comment by mixedpuppy** [comment]
@collectedmind, is this change ok from your end?

**Comment by collectedmind** [comment]
I am fine with that. Agree it should be shared so I will add it to the list of code to revisit.  Tested it locally and all is well with saving.

**Comment by gijsk** [comment]
Thanks!

**Pull request merged**
